#!/bin/bash

# Use this script to sync your local copy to either staging or live site
# Be sure to edit sync-push-exclude for filepaths & files to exclude
# usage ./sync-push [staging|production] 		(dry-run to staging or production)
# usage ./sync-push [staging|production] live 	(for real to staging or production)

# Default to staging
REMOTE_HOST=solegraphics.com
REMOTE_PATH=www/emergencyreporting/global/
ENVIRONMENT=staging

PRODUCTION_HOST=solegraphics.com
PRODUCTION_PATH=www/emergencyreporting/global/

REMOTE_USER=solegrap
LOCAL_PATH=./

# Recursive, Verbose, Checksum (rather than mod-time + size)
RSYNC_OPTIONS=rvc

MODE=TEST
#OPT_DELETE=--delete
OPT_DELETE=
OPT_DRY_RUN=--dry-run
OPT_EXCLUDES=

# invalid argument
if [[ "$1" != "staging" &&  "$1" != "production" &&  "$1" != "live" && "$1" != "" ]]; then
	echo "Usage: ./sync-push [staging|production] [live](to run for real)"
	exit 1
fi

# Custom excludes
if [ -e sync-push-exclude ]; then
	echo "Loading excludes options from 'sync-push-exclude'"
	OPT_EXCLUDES="--exclude-from=sync-push-exclude"
fi

# ./sync-push production
# pushing to production environment
if [ "$1" == "production" ]; then
	ENVIRONMENT=production
	REMOTE_HOST=$PRODUCTION_HOST
	REMOTE_PATH=$PRODUCTION_PATH
fi

# Do it for reals
if [[ "$1" == "live" || "$2" == "live" ]]; then
	MODE=LIVE
	OPT_DRY_RUN=
fi

doSync() {
	rsync -"$RSYNC_OPTIONS" "$OPT_DELETE" "$OPT_DRY_RUN" "$OPT_EXCLUDES" "$LOCAL_PATH" "$REMOTE_USER"@"$REMOTE_HOST":"$REMOTE_PATH"
}
# CMD here is to hold a clone of doSync to output
CMD="rsync -$RSYNC_OPTIONS $OPT_DELETE $OPT_DRY_RUN $OPT_EXCLUDES $LOCAL_PATH $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH"
echo -e "
--------------------------------------------------------------------------
Running in \033[32m$MODE\033[0m mode to \033[32m$ENVIRONMENT\033[0m:
$CMD
--------------------------------------------------------------------------"

doSync;

echo
echo -e "\033[32mAll done.\033[0m"

if [ $MODE != "LIVE" ]; then
    echo -e "If everything looks good, enter './sync-push $ENVIRONMENT live' to run for realsies"
fi

